#server settings
server:
    port : 9090
    address : 0.0.0.0
    contextPath : /
    #Tomcat specifics
#    ssl:
#      key-store-password: 7632785
#      key-store-type: PKCS12
#      key-store: /Users/jafir/Downloads/upload/cert/*.nofoo.cn.pfx
    tomcat:
        accessLogEnabled : true
        protocolHeader : x-forwarded-proto
        remoteIpHeader : x-forwarded-for
        basedir:
        backgroundProcessorDelay : 30 # secs
spring:
  mvc:
    view:
      prefix: /
      suffix: .html   # 静态网页资源配置
    throw-exception-if-no-handler-found: true  #全局异常处理
    static-path-pattern: /res/**
  resources:
    static-locations: classpath:/static/ , file:/Users/jafir/Downloads/upload/ #静态资源配置
#    add-mappings: false #关闭工程资源映射，全局异常处理按道理要关闭，但是不推荐，这里不关闭
  profiles :
    active: RELEASE
  jackson:
    date-format : yyyy-MM-dd HH:mm:ss
  datasource:
#  local  3306   root 7632785
#    url: jdbc:mysql://localhost:3306/gps?useSSL=false&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://47.108.82.91:3306/gps?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClass: com.mysql.jdbc.Driver
    username: root
    password: Wanglei1994
    initialSize: 2
    minIdl: 2
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 300000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    #validationQuery: select "1"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  # 解决http返回数据中文乱码
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true



mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
#  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
    level:
       com.ibatis: DEBUG
       cn.jafir.springboot: TRACE
